# Generated by Django 5.0.4 on 2024-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enqry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=14)),
                ('p_when', models.DateField()),
                ('p_events', models.CharField(max_length=100)),
            ],
        ),
    ]
